linters:
  disable-all: true
  enable:
    # - deadcode
    - errcheck
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    # - misspell
    - nolintlint
    - goimports
    - nakedret
    - unconvert
    - whitespace
    - gosimple
    - govet
    - ineffassign
    - gocritic
    - revive
linters-settings:
  nolintlint:
    allow-unused: false
    allow-leading-space: false
    require-specific: true
