// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: 3_grpc_candles/candlespb/CandlesService.proto

package candlespb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Period int32

const (
	Period_PERIOD_1M  Period = 0
	Period_PERIOD_2M  Period = 1
	Period_PERIOD_10M Period = 2
)

// Enum value maps for Period.
var (
	Period_name = map[int32]string{
		0: "PERIOD_1M",
		1: "PERIOD_2M",
		2: "PERIOD_10M",
	}
	Period_value = map[string]int32{
		"PERIOD_1M":  0,
		"PERIOD_2M":  1,
		"PERIOD_10M": 2,
	}
)

func (x Period) Enum() *Period {
	p := new(Period)
	*p = x
	return p
}

func (x Period) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Period) Descriptor() protoreflect.EnumDescriptor {
	return file__3_grpc_candles_candlespb_CandlesService_proto_enumTypes[0].Descriptor()
}

func (Period) Type() protoreflect.EnumType {
	return &file__3_grpc_candles_candlespb_CandlesService_proto_enumTypes[0]
}

func (x Period) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Period.Descriptor instead.
func (Period) EnumDescriptor() ([]byte, []int) {
	return file__3_grpc_candles_candlespb_CandlesService_proto_rawDescGZIP(), []int{0}
}

type CandleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Instrument string                 `protobuf:"bytes,1,opt,name=instrument,proto3" json:"instrument,omitempty"`
	Ts         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ts,proto3" json:"ts,omitempty"`
	Period     Period                 `protobuf:"varint,3,opt,name=period,proto3,enum=candles.Period" json:"period,omitempty"`
	Open       float64                `protobuf:"fixed64,4,opt,name=open,proto3" json:"open,omitempty"`
	High       float64                `protobuf:"fixed64,5,opt,name=high,proto3" json:"high,omitempty"`
	Low        float64                `protobuf:"fixed64,6,opt,name=low,proto3" json:"low,omitempty"`
	Close      float64                `protobuf:"fixed64,7,opt,name=close,proto3" json:"close,omitempty"`
}

func (x *CandleResponse) Reset() {
	*x = CandleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file__3_grpc_candles_candlespb_CandlesService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CandleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandleResponse) ProtoMessage() {}

func (x *CandleResponse) ProtoReflect() protoreflect.Message {
	mi := &file__3_grpc_candles_candlespb_CandlesService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandleResponse.ProtoReflect.Descriptor instead.
func (*CandleResponse) Descriptor() ([]byte, []int) {
	return file__3_grpc_candles_candlespb_CandlesService_proto_rawDescGZIP(), []int{0}
}

func (x *CandleResponse) GetInstrument() string {
	if x != nil {
		return x.Instrument
	}
	return ""
}

func (x *CandleResponse) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

func (x *CandleResponse) GetPeriod() Period {
	if x != nil {
		return x.Period
	}
	return Period_PERIOD_1M
}

func (x *CandleResponse) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *CandleResponse) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *CandleResponse) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *CandleResponse) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

type CandleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Instrument string `protobuf:"bytes,1,opt,name=instrument,proto3" json:"instrument,omitempty"`
	Period     Period `protobuf:"varint,2,opt,name=period,proto3,enum=candles.Period" json:"period,omitempty"`
}

func (x *CandleRequest) Reset() {
	*x = CandleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file__3_grpc_candles_candlespb_CandlesService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CandleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandleRequest) ProtoMessage() {}

func (x *CandleRequest) ProtoReflect() protoreflect.Message {
	mi := &file__3_grpc_candles_candlespb_CandlesService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandleRequest.ProtoReflect.Descriptor instead.
func (*CandleRequest) Descriptor() ([]byte, []int) {
	return file__3_grpc_candles_candlespb_CandlesService_proto_rawDescGZIP(), []int{1}
}

func (x *CandleRequest) GetInstrument() string {
	if x != nil {
		return x.Instrument
	}
	return ""
}

func (x *CandleRequest) GetPeriod() Period {
	if x != nil {
		return x.Period
	}
	return Period_PERIOD_1M
}

var File__3_grpc_candles_candlespb_CandlesService_proto protoreflect.FileDescriptor

var file__3_grpc_candles_candlespb_CandlesService_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x33, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73,
	0x2f, 0x63, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x70, 0x62, 0x2f, 0x43, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x63, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd5, 0x01, 0x0a, 0x0e, 0x43, 0x61,
	0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x2a, 0x0a, 0x02,
	0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74, 0x73, 0x12, 0x27, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x69,
	0x6f, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x63, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x73, 0x2e, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x52, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x04, 0x6f, 0x70, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x67, 0x68, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x04, 0x68, 0x69, 0x67, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x77,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x6f, 0x77, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6c, 0x6f, 0x73, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x63, 0x6c, 0x6f, 0x73,
	0x65, 0x22, 0x58, 0x0a, 0x0d, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x27, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x63, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x2e, 0x50, 0x65, 0x72,
	0x69, 0x6f, 0x64, 0x52, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x2a, 0x36, 0x0a, 0x06, 0x50,
	0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x45, 0x52, 0x49, 0x4f, 0x44, 0x5f,
	0x31, 0x4d, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x45, 0x52, 0x49, 0x4f, 0x44, 0x5f, 0x32,
	0x4d, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x45, 0x52, 0x49, 0x4f, 0x44, 0x5f, 0x31, 0x30,
	0x4d, 0x10, 0x02, 0x32, 0x50, 0x0a, 0x0e, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x07, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73,
	0x12, 0x16, 0x2e, 0x63, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x2e, 0x43, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x63, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x73, 0x2e, 0x43, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x1a, 0x5a, 0x18, 0x33, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x5f,
	0x63, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x2f, 0x63, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x73, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file__3_grpc_candles_candlespb_CandlesService_proto_rawDescOnce sync.Once
	file__3_grpc_candles_candlespb_CandlesService_proto_rawDescData = file__3_grpc_candles_candlespb_CandlesService_proto_rawDesc
)

func file__3_grpc_candles_candlespb_CandlesService_proto_rawDescGZIP() []byte {
	file__3_grpc_candles_candlespb_CandlesService_proto_rawDescOnce.Do(func() {
		file__3_grpc_candles_candlespb_CandlesService_proto_rawDescData = protoimpl.X.CompressGZIP(file__3_grpc_candles_candlespb_CandlesService_proto_rawDescData)
	})
	return file__3_grpc_candles_candlespb_CandlesService_proto_rawDescData
}

var file__3_grpc_candles_candlespb_CandlesService_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file__3_grpc_candles_candlespb_CandlesService_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file__3_grpc_candles_candlespb_CandlesService_proto_goTypes = []interface{}{
	(Period)(0),                   // 0: candles.Period
	(*CandleResponse)(nil),        // 1: candles.CandleResponse
	(*CandleRequest)(nil),         // 2: candles.CandleRequest
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file__3_grpc_candles_candlespb_CandlesService_proto_depIdxs = []int32{
	3, // 0: candles.CandleResponse.ts:type_name -> google.protobuf.Timestamp
	0, // 1: candles.CandleResponse.period:type_name -> candles.Period
	0, // 2: candles.CandleRequest.period:type_name -> candles.Period
	2, // 3: candles.CandlesService.Candles:input_type -> candles.CandleRequest
	1, // 4: candles.CandlesService.Candles:output_type -> candles.CandleResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file__3_grpc_candles_candlespb_CandlesService_proto_init() }
func file__3_grpc_candles_candlespb_CandlesService_proto_init() {
	if File__3_grpc_candles_candlespb_CandlesService_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file__3_grpc_candles_candlespb_CandlesService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CandleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file__3_grpc_candles_candlespb_CandlesService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CandleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file__3_grpc_candles_candlespb_CandlesService_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file__3_grpc_candles_candlespb_CandlesService_proto_goTypes,
		DependencyIndexes: file__3_grpc_candles_candlespb_CandlesService_proto_depIdxs,
		EnumInfos:         file__3_grpc_candles_candlespb_CandlesService_proto_enumTypes,
		MessageInfos:      file__3_grpc_candles_candlespb_CandlesService_proto_msgTypes,
	}.Build()
	File__3_grpc_candles_candlespb_CandlesService_proto = out.File
	file__3_grpc_candles_candlespb_CandlesService_proto_rawDesc = nil
	file__3_grpc_candles_candlespb_CandlesService_proto_goTypes = nil
	file__3_grpc_candles_candlespb_CandlesService_proto_depIdxs = nil
}
